# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 14:13
from __future__ import unicode_literals

from django.db import migrations


def create_default_user(apps, schema_editor):
    user_model = apps.get_model('accounts', 'User')
    user, _ = user_model.objects.get_or_create(username='root', defaults={
        'password': u'pbkdf2_sha256$30000$GVj1zgi4YujM$lk+8dShuC1JiA/nB8zoxAU0neOzPr0xOme4HU7oLjKE='
    })

    user.is_superuser = True
    user.is_staff = True
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_office_model'),
    ]

    operations = [
        migrations.RunPython(create_default_user, reverse_code=lambda *args, **kwargs: True),
    ]
