# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
